apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  labels:
    app: n8n
  namespace: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: n8n
    spec:
      restartPolicy: Always
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["n8n", "start"]
        ports:
        - containerPort: 5678
        env:
        - name: N8N_HOST
          value: "0.0.0.0"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: N8N_DATA_FOLDER
          value: "/"
        volumeMounts:
        - name: n8n-data
          mountPath: /
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "10Gi"
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: n8n-data 