apiVersion: v1
kind: Service
metadata:
  namespace: n8n
  name: n8n
  labels:
    app: n8n
spec:
  type: NodePort
  selector:
    app: n8n
  ports:
    - protocol: TCP
      name: http
      port: 5678
      targetPort: 5678
      nodePort: 30001 