apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 
---
apiVersion: "openebs.io/v1alpha1"
kind: MayastorPool
metadata:
  name: n8n-pool
  namespace: n8n
spec:
  node: talos-38w-t3u
  disks: ["/dev/sdb"]
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: n8n-storage-class
  namespace: n8n
parameters:
  repl: '1'
  protocol: 'nvmf'
provisioner: io.openebs.csi-mayastor