apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: n8n-storage
  namespace: n8n
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-data
  namespace: n8n
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/n8n"
  storageClassName: n8n-storage
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: n8n-storage
  volumeMode: Filesystem 